name: mambair
channels:
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  - cmake
  - ninja
  - cudatoolkit=12.1
  - ffmpeg
  - filelock
  - numpy
  - pillow
  - scipy
  - typing_extensions

