# general settings for image SR training
name: MambaIRv2Yolo_Xview_x2
model_type: MambaIRv2YoloModel
scale: 2
num_gpu: 2
manual_seed: 10

# settings for joint mambaIR + Yolo training
yolo_weight: 1
sr_weight: 1

yolo_losses:
  box_gain: 7.5 #(7.5)
  dlf_gain: 1.5 #(1.5)
  cls_gain: 0.5 #(0.5)

# dataset and data loader settings
datasets:
  train:
    task: SR
    name: DF2K
    type: PairedImageLabelDataset
    dataroot_gt:
      - /mnt/2tb-2/satellitepy/data/xview/sets_gsd_30/train/images/
    dataroot_lq:
      - /mnt/2tb-2/satellitepy/data/xview/sets_gsd_60/train/images/
    dataroot_label:
      - /mnt/2tb-2/satellitepy/data/xview/sets_gsd_30/train/labels_yolo/
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 384

    # Augmentations
    ## Set all to 0 for no augmentations
    augmentations:
      fliplr: 0.8 # Probability
      flipud: 0.2 # Probability
      noise_per_channel: 0.1 # Add a value (0,1) to all pixels in a Normalized image.


    # data loader
    use_shuffle: true
    num_worker_per_gpu: 32
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: Set14
    type: PairedImageLabelDataset
    dataroot_gt: /mnt/2tb-2/satellitepy/data/xview/sets_gsd_30/test/images/
    dataroot_lq: /mnt/2tb-2/satellitepy/data/xview/sets_gsd_60/test/images/
    dataroot_label: /mnt/2tb-2/satellitepy/data/xview/sets_gsd_30/test/labels_yolo/
    filename_tmpl: '{}'
    io_backend:
      type: disk


# network structures
network_g:
  type: MambaIRv2
  upscale: 2
  in_chans: 3
  img_size: 64
  img_range: 1.
  embed_dim: 174
  d_state: 16
  depths: [6, 6, 6,6,6,6]
  num_heads: [6,6,6,6,6,6]
  window_size: 16
  inner_rank: 64
  num_tokens: 128
  convffn_kernel_size: 5
  mlp_ratio: 2.
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'


# path
path:
  # for classic SRx4, we use the x2 Model to initialize and halve the training iteration and lr for fast training
  pretrain_network_g: /home/louis/workspace/MambaIR/pretrained/mambairv2_classicSR_Base_x4.pth
  strict_load_g: false
  resume_state: ~
  experiments_root: /mnt/2tb-2/experiments_mambair-yolo_xview


# training settings
train:
  optim_g:
    type: Adam
    # lr: !!float 2e-4
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    # milestones: [ 250000, 400000, 450000, 475000 ]
    milestones: [ 125000, 200000, 225000, 237500 ]
    gamma: 0.5

  total_iter: 500000
#  total_iter: 6000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
# validation settings
val:
  val_freq: !!float 5e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true



# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 9e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500